#
###################################
# Site wide configuration
####################################
#
title: huchuanwei
email: huchuanwei1018@gmail.com
description: huchuanwei's blog,powered by jekyll.
url: https://www.huchuanwei.com # the base hostname & protocol for your site
keywords: ["jekyll", "python", "cuda","blog"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Shanghai
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

plugins:
  - jekyll-gist
  - jemoji

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: huchuanwei
  avatar: avatar.png
  job: "Computing Parallel Engineer"
  bio: "A Engineer who loves design awesome things. Working for HuangPu at in GuangZhou, China."
  email: huchuanwei1018@gmail.com
  disqus-shortname: #username
  twitter:  #username
  facebook: #username
  google:
    plus: #username
    analytics: #UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  baiduTongji:
    config: true
  bing-verify:
  github: chuanweihu #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username