#
###################################
# Site wide configuration
####################################
#
title: huchuanwei
email: huchuanwei1018@gmail.com
description: huchuanwei's blog,powered by jekyll.
url: https://www.huchuanwei.com # the base hostname & protocol for your site
keywords: ["jekyll", "python", "cuda","blog"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Shanghai
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

plugins:
  - jekyll-gist
  - jemoji

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: huchuanwei
  avatar: avatar.png
  job: "Computing Parallel Engineer"
  bio: "A Engineer who loves design awesome things."
  email: huchuanwei1018@gmail.com
  disqus-shortname: #username
  twitter:  #username
  facebook: #username
  google:
    plus:
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: chuanweihu #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
  payImage1: wx1.png
  payImage2: wx2.png
  payImage3: zfb.png